# See https://tex.stackexchange.com/questions/40738/how-to-properly-make-a-latex-project and http://mirrors.ibiblio.org/CTAN/support/latex-make/latex-make.pdf

# ToDo: Incorporate the figures that bundles.pdf depends on
bundles.pdf: bundles.tex
	pdflatex bundles
	pdflatex bundles
