from os.path import join
import os
Import('PYTHON DDA RDA')

this_file = (lambda x:x).func_code.co_filename
here = lambda x: join(os.path.abspath(os.path.dirname(this_file)), x)

root = lambda x: join(GetLaunchDir(), x)
r_times = root(DDA('r_times'))
lp_hr = root(DDA('low_pass_heart_rate'))
respiration = root(DDA('respiration'))
expert = root(RDA('summary_of_training'))

records_list = os.listdir(r_times)
records = lambda path: [join(root(path), x) for x in records_list]
r_time_records = records(DDA('r_times'))
lp_hr_records = records(DDA('low_pass_heart_rate'))

records_string = ''
for x in records_list:
    records_string += '%s '%x
a_records_string = ''
for x in records_list:
    if x.startswith('a'):
        a_records_string += '%s '%x
    
env = Environment()
env.Command(
    lp_hr_records,
    r_time_records+['rr2hr.py'],
    PYTHON + ' %s %s %s '%(here('rr2hr.py'), r_times, lp_hr) + records_string
    )
resp_records = records(DDA('respiration'))
annotations = root(RDA('summary_of_training'))
apnea = root(DDA(''))
respiration = root(DDA('respiration'))
env.Command(
    resp_records,
    r_time_records+['respire.py'],
    PYTHON + ' %s %s %s %s %s '%(here('respire.py'), annotations, r_times,
                                 apnea, respiration)
    )
initial_models = tuple(root(DDA(x)) for x in
                  ('init_A2', 'mod_C1', 'init_H', 'init_M', 'init_L'))
args = (here('mod_init.py'), lp_hr, respiration, expert)
env.Command(
    initial_models,
    args,
    PYTHON + (len(args)*' %s ')%args + root(DDA(''))
    )
env.Command(
    root(DDA('mod_H')),
    root(DDA('init_H')),
    PYTHON + ('%s --hr_dir=%s --resp_dir=%s --expert=%s --iterations=20 ' +
     '%s %s a06 b01 a11 a10 a17 a18 a05 b03 a16 a20 a09 a14 a07 a19 b02 a02 a08 a13 a03 a01 a04 a12 a15')%(here('ApTrain.py'), lp_hr, respiration, expert,
                            root(DDA('init_H')), root(DDA('mod_H'))))
env.Command(
    root(DDA('mod_M')),
    root(DDA('init_M')),
    PYTHON + ('%s --hr_dir=%s --resp_dir=%s --expert=%s --iterations=20 ' +
     '%s %s c07 c08 b04 a06 b01 ')%(here('ApTrain.py'), lp_hr, respiration, expert,
                            root(DDA('init_M')), root(DDA('mod_M'))))
env.Command(
    root(DDA('mod_L')),
    root(DDA('init_L')),
    PYTHON + ('%s --hr_dir=%s --resp_dir=%s --expert=%s --iterations=20 ' +
     '%s %s c04 c09 c03 c10 c02 c06 c05 c01 c07 c08 b04')%(here('ApTrain.py'), lp_hr, respiration, expert,
                            root(DDA('init_L')), root(DDA('mod_L'))))
env.Command(
    root(DDA('mod_A2')),
    root(DDA('init_A2')),
    PYTHON + ('%s --hr_dir=%s --resp_dir=%s --iterations=20 %s %s %s'%(
        here('ApTrain.py'), lp_hr, respiration,
        root(DDA('init_A2')),  # Initial model
        root(DDA('mod_A2')),   # Trained model
        a_records_string       # List of records to train on
    )))
com_str = PYTHON + here('DoubleClassify.py')
com_str += ' --Lmodel=%s '%root(DDA('mod_L')) + '--Mmodel=%s '%root(DDA('mod_M'))
com_str += ' --Hmodel=%s --Single'%root(DDA('mod_H'))
com_str +=  ' %s %s %s %s '%(root(DDA('mod_A2')), root(DDA('mod_C1')),
                             root(DDA('low_pass_heart_rate')), root(DDA('respiration')))
#com_str +=  (4*' %s ')%(DDA(x) for x in
#             ('mod_A2', 'mod_C1', 'low_pass_heart_rate', 'respiration'))
env.Command(
    root(DDA('pass1_report')),
    list([root(DDA(x))
          for x in ('mod_L', 'mod_M', 'mod_H', 'mod_A2', 'mod_C1')]),
    com_str + records_string + '|tee %s'%root(DDA('pass1_report'))
    )

#Local Variables:
#mode:python
#End:
