from os.path import join
import os
Import('PYTHON DDA RDA')

root = lambda x: join(GetLaunchDir(), x)
here = lambda x: join(root('code/applications/apnea'), x)
r_times = root(DDA('r_times'))
lp_hr = root(DDA('low_pass_heart_rate'))
apnea = root(DDA(''))
annotations = root(RDA('summary_of_training'))
respiration = root(DDA('respiration'))

records_list = os.listdir(r_times)
records = lambda path: [join(root(path), x) for x in records_list]
r_time_records = records('derived_data/apnea/r_times')
lp_hr_records = records('derived_data/apnea/low_pass_heart_rate')
resp_records = records('derived_data/apnea/respiration')

records_string = ''
for x in records_list:
    records_string += '%s '%x
env = Environment()
env.Command(
    lp_hr_records,
    r_time_records+['rr2hr.py'],
    PYTHON + ' %s %s %s '%(here('rr2hr.py'), r_times, lp_hr) + records_string
    )
env.Command(
    resp_records,
    r_time_records+['respire.py'],
    PYTHON + ' %s %s %s %s %s '%(here('respire.py'), annotations, r_times,
                                 apnea, respiration)
    )

#Local Variables:
#mode:python
#End:
