'''plotscripts/SConscript

Scripts in this directory plot data that other code produced.  They
should not write anything except the resulting plots.
'''
import os
import os.path
from os.path import join
Import('PYTHON2 DDA RDA')  # matplotlib does not run under python3

this_file = (lambda x:x).func_code.co_filename
here = lambda x: join(os.path.abspath(os.path.dirname(this_file)), x)

root = lambda x: join(GetLaunchDir(), x)
fig = lambda x: join(root('figs'), x)
lp_hr = lambda x: root(DDA(join('low_pass_heart_rate', x)))
r_times = lambda x: root(DDA(join('r_times', x)))
resp = lambda x: root(DDA(join('respiration', x)))
seg = root(DDA('a03er_seg'))

apnea_sgram_files = (here('apnea_sgram.py'), r_times('a11'), lp_hr('a11'),
                     root(RDA('summary_of_training')))
env = Environment()

apnea_ts_figs = tuple(
    fig(x) for x in ('a03erA.pdf', 'a03erN.pdf', 'a03erHR.pdf', 'ApneaNLD.pdf'))
apnea_ts_files = (here('apnea_ts_plots.py'), seg) + \
    tuple(lp_hr(x) for x in ('a03', 'a01', 'a12'))
env.Command(
    apnea_ts_figs,
    apnea_ts_files,
    PYTHON2 + ((len(apnea_ts_figs)+len(apnea_ts_files))*' %s')%(
        apnea_ts_files + apnea_ts_figs)
    )
env.Command(
    fig('sgram.pdf'),
    apnea_sgram_files,
    PYTHON2 + (len(apnea_sgram_files)*' %s ')%apnea_sgram_files+fig('sgram.pdf')
    )

LDA_figs = tuple(fig(x) for x in ('LDA1.pdf', 'LDA2.pdf'))
LDA_src = (here('LDA.py'),) + tuple(root(DDA(x)) for x in (
        'mean.resp', 'AA.resp', 'AN.resp', 'C.resp')) # FixMe: Depends
                                                      # on contents of
                                                      # DDA(respiration)
env.Command(
    LDA_figs,
    LDA_src,
    PYTHON2 + ((len(LDA_figs)+len(LDA_src))*' %s')%(LDA_src + LDA_figs)
    )

#Local Variables:
#mode:python
#End:
